version: '3.5'

services:
<<<<<<< HEAD
  cobalt-api:
      build: .
      init: true
      restart: unless-stopped
      container_name: cobalt-api
      environment:
          - apiPort=9000
          - apiURL=https://co.wuk.sh/
          - apiName=coprox
          - ENABLED_PROXY_PROVIDERS=ivpn,mullvad
          - PROXY_EVERYTHING=0
          - USE_CHAINING=1
      ports:
          - 127.0.0.1:9000:9000
      depends_on:
          - ivpn
          - mullvad
  web:
        build: .
=======
    cobalt-api:
        image: ghcr.io/wukko/cobalt:latest
        restart: unless-stopped
        container_name: cobalt-api

        # if container doesn't run detached on your machine, uncomment the next line:
        #tty: true

        ports:
            - 9000:9000/tcp
            # if you're using a reverse proxy, uncomment the next line:
            #- 127.0.0.1:9000:9000

        environment:
            - apiPort=9000
            # replace apiURL with your instance's target url in same format
            - apiURL=https://co.wuk.sh/
            # replace apiName with your instance's distinctive name
            - apiName=eu-nl
            # if you want to use cookies when fetching data from services, uncomment the next line
            #- cookiePath=cookies.json
            # see src/modules/processing/cookie/cookies_example.json for example file.

        labels:
            - com.centurylinklabs.watchtower.scope=cobalt

    cobalt-web:
        image: ghcr.io/wukko/cobalt:latest
>>>>>>> no-migration
        restart: unless-stopped
        container_name: cobalt-web
        ports:
            - 9001:9001/tcp
        environment:
            - webPort=9001
<<<<<<< HEAD
            - webURL=https://co.wukko.me/
            - apiURL=https://co.wuk.sh/


  mullvad:
      image: qmcgaw/gluetun
      container_name: mullvad
      cap_add:
          - NET_ADMIN
      devices:
          - /dev/net/tun:/dev/net/tun
      environment:
          - VPN_SERVICE_PROVIDER=mullvad
          - DOT=off
          - VPN_TYPE=wireguard
          # copy this from mullvad generated wg.conf
          - WIREGUARD_PRIVATE_KEY=
          # also this
          - WIREGUARD_ADDRESSES=
          # also this (if different)
          - DNS_ADDRESS=10.64.0.1
          # any server, preferably one close to your server
          - SERVER_HOSTNAMES=se-got-wg-001
      restart: unless-stopped
  mullvad_proxy:
        image: serjs/go-socks5-proxy
        network_mode: "container:mullvad"

  ivpn:
        image: qmcgaw/gluetun
        container_name: ivpn
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun:/dev/net/tun
        environment:
            - VPN_SERVICE_PROVIDER=ivpn
            - DOT=off
            - VPN_TYPE=wireguard
            # pull this from ivpn wg.conf
            - WIREGUARD_PRIVATE_KEY=
            # also this
            - WIREGUARD_ADDRESSES=
            # also this (if different)
            - DNS_ADDRESS=172.16.0.1
            # any server, preferably one close to your server
            - SERVER_HOSTNAMES=nl1.wg.ivpn.net
        restart: unless-stopped
  ivpn_proxy:
        image: serjs/go-socks5-proxy
        network_mode: "container:ivpn"
=======
            # replace webURL with your instance's target url in same format
            - webURL=https://cobalt.tools/
            # replace apiURL with preferred api instance url
            - apiURL=https://co.wuk.sh/

        labels:
            - com.centurylinklabs.watchtower.scope=cobalt

    # update the cobalt image automatically with watchtower
    watchtower:
        image: ghcr.io/containrrr/watchtower
        restart: unless-stopped
        command: --cleanup --scope cobalt --interval 900
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
>>>>>>> no-migration
